feat: integrate Deno KV, rewrite entire codebase (#4)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,7 +1,7 @@
 name: Scrape
 on:
   schedule:
-    - cron: "*/7 * * * *"
+    - cron: "*/8 * * * *"
   workflow_dispatch:
 jobs:
   scrape:
@@ -17,22 +17,35 @@ jobs:
         uses: denoland/setup-deno@v1
         with:
           deno-version: v1.x
-
-      - id: scrape
-        name: "(run) main.ts"
-        run: deno run --unstable --allow-all main.ts
-
-      - name: "upload artifacts"
-        uses: actions/upload-artifact@v3
-        with:
-          path: ${{ steps.scrape.outputs.filename }}
-
-      - name: "commit + push"
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - 
+        name: "(setup) git"
         run: |
           git config --local user.email "github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
+
+      - id: scrape
+        name: "(run) deno task scrape"
+        env:
+          DENO_KV_PATH: ${{ secrets.DENO_KV_PATH }}
+          DENO_KV_ACCESS_TOKEN: ${{ secrets.DENO_KV_ACCESS_TOKEN }}
+        run: deno task scrape
+
+      - if: ${{ steps.scrape.outputs.filename == '' }}
+        name: "no new photo captured"
+        run: |
+          echo -e $'\e[1;7;31mERROR\e[0m \e[1;3;91mNo new photo captured!\e[0m'
+          exit 1
+        
+      - if: ${{ success() }}
+        name: "(run) upload artifacts"
+        uses: actions/upload-artifact@v3
+        with:
+          path: ${{ steps.scrape.outputs.filename }}
+        
+      - name: "(git) commit + push"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
           git add .
           git commit -m "[$(date +"%F %H:%M:%S %Z")]: new photo captured"
           git push
